platform :ios, '7.0'
workspace 'Pelotonia'
pod 'ASIHTTPRequest', '~>1.8.1'
pod 'Reachability', '~>3.1.1'
pod 'Appirater', '~>2.0.2'
pod 'hpple', '~>0.2.0'
pod 'MBProgressHUD', '~>0.8'
pod 'SDWebImage', '~>3.5.2'
pod 'ECSlidingViewController', '~>2.0.0'
pod 'AAPullToRefresh'
