platform :ios, '7.0'
workspace 'Pelotonia'
pod 'AFNetworking'
pod 'Appirater', '~>2.0.2'
pod 'MBProgressHUD', '~>0.8'
pod 'SDWebImage', '~>3.5.2'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'ECSlidingViewController', '~>2.0.0'
pod 'AAPullToRefresh'
pod 'MagicalRecord/Shorthand'

